name: share4D
favicon: null
layout_spectrum: 0.25272
typography_spectrum: 0.373040511040017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4bc64a'
    - '#93d894'
    - '#2e373c'
    - '#99a3a5'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.9374491160269827
  rhythmicContrast: 1
purpose: []
